# Generated by Django 6.1.1 on 2026-10-05 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_googleintegration'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='private_pin_hash',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
