# Generated by Django 6.1.1 on 2026-10-05 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_private_pin_hash'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GoogleIntegration',
        ),
    ]
