# Generated by Django 6.1.1 on 2026-09-10 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='telegram_file_unique_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
