# Generated by Django 6.1.1 on 2026-09-10 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_media_telegram_file_unique_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='telegram_thumbnail_file_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
