# Generated by Django 6.1.1 on 2026-09-11 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0003_media_telegram_thumbnail_file_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='taken_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
