# Generated by Django 6.1.1 on 2026-09-11 05:38

from django.db import migrations
from django.db.models import F

def backfill_taken_at(apps, schema_editor):
    Media = apps.get_model('media', 'Media')
    Media.objects.filter(taken_at__isnull=True).update(taken_at=F('created_at'))

def reverse_backfill(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('media', '0004_media_taken_at'),
    ]

    operations = [
        migrations.RunPython(backfill_taken_at, reverse_backfill),
    ]
