# Generated by Django 6.1.1 on 2026-09-11 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0005_backfill_taken_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='file_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
