# Generated by Django 6.1.1 on 2026-09-11 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0006_media_file_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='media',
            name='status',
            field=models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='processing', max_length=20),
        ),
        migrations.AddField(
            model_name='media',
            name='temp_file_path',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='media',
            name='upload_error',
            field=models.TextField(blank=True, null=True),
        ),
    ]
