# Generated by Django 6.1.1 on 2026-09-14 11:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0008_sharedlink'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('preview', 'Preview image'), ('stream', 'Playback video')], max_length=20)),
                ('mime_type', models.CharField(max_length=100)),
                ('file_size', models.BigIntegerField(default=0)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('telegram_message_id', models.BigIntegerField(blank=True, null=True)),
                ('telegram_file_id', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='media',
            name='taken_at_source',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='media',
            name='status',
            field=models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('duplicate', 'Duplicate')], default='processing', max_length=20),
        ),
        migrations.AddIndex(
            model_name='media',
            index=models.Index(fields=['user', 'is_deleted', '-taken_at', '-created_at'], name='media_timeline_idx'),
        ),
        migrations.AddField(
            model_name='mediavariant',
            name='media',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='media.media'),
        ),
        migrations.AddConstraint(
            model_name='mediavariant',
            constraint=models.UniqueConstraint(fields=('media', 'kind'), name='unique_media_variant_kind'),
        ),
    ]
