# Generated by Django 6.1.1 on 2026-09-21 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0009_variants_timeline_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='media',
            name='location_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='media',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
