# Generated by Django 6.1.1 on 2026-10-05 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0011_media_source_external_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='clip_embedding',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
