# Generated by Django 6.1.1 on 2026-10-05 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0012_media_clip_embedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
